--- 
#level 1
- :from_top: 3
  :duration: 10
  :font_color: 0xFF000000
  :player_image: angry_birds/pig.png
  :player_shield_image: angry_birds/soldier_pig.png
  :ball_image: angry_birds/red_bird.png
  :background_image: angry_birds/angry_birds_green_field.png
  :music: angry_birds/angry_birds_music.mp3
#level 2
- :from_left: 2
  :xinc: 15
  :duration: 10
  :font_color: 0xFF000000
  :player_image: angry_birds/pig.png
  :player_shield_image: angry_birds/soldier_pig.png
  :ball_image: angry_birds/yellow_bird.png
  :background_image: angry_birds/angry_birds_sun.png
#level 3
- :from_right: 3
  :duration: 10
  :font_color: 0xFF000000
  :player_image: angry_birds/pig.png
  :player_shield_image: angry_birds/soldier_pig.png
  :ball_image: angry_birds/black_bird.png
  :background_image: angry_birds/angry_birds_blue_bg.png
#level 4
- :from_top: 5
  :duration: 10
  :font_color: 0xFF000000
  :player_image: angry_birds/pig.png
  :player_shield_image: angry_birds/soldier_pig.png
  :ball_image: angry_birds/white_bird.png
  :background_image: angry_birds/angry_birds_sky.png
#level 5
- :from_custom:
     :count: 2
     :xinc: lambda {|x,y,xs,ys| 100*(Math.sin(y.to_f/100)) + xs}
     :yinc: lambda {|x,y,xs,ys| y + 10}
     :xinit: lambda {rand(600) + 100}
     :yinit: lambda {0}
  :duration: 10
  :font_color: 0xFF000000
  :player_image: angry_birds/mustache_pig.png
  :player_shield_image: angry_birds/mustache_soldier_pig.png
  :ball_image: angry_birds/green_bird.png
  :background_image: angry_birds/angry_birds_green_field.png
