--- 
#level 1
- :from_top: 1
  :duration: 10
  :player_image: default/player1.png
  :player_shield_image: default/player1_neon.png
  :ball_image: default/asteroid.png
  :background_image: default/orange_nebula_stars.jpg
#level 2
- :from_top: 3
  :duration: 10
  :player_image: default/player1.png	
  :player_shield_image: default/player1_neon.png
  :ball_image: default/asteroid.png
  :background_image: default/orange_nebula_stars.jpg
#level 3
- :from_left: 3
  :duration: 10
  :player_image: default/player1.png
  :player_shield_image: default/player1_neon.png
  :ball_image: default/asteroid.png
  :background_image: default/orange_nebula_stars.jpg
#level 4
- :from_bottom: 3
  :duration: 10
  :player_image: default/player1.png
  :player_shield_image: default/player1_neon.png
  :ball_image: default/asteroid.png
  :background_image: default/orange_nebula_stars.jpg
#level 5
- :from_top: 5
  :duration: 10
  :player_image: default/player1.png
  :player_shield_image: default/player1_neon.png
  :ball_image: default/asteroid.png
  :background_image: default/orange_nebula_stars.jpg
#level 6
- :from_right: 5
  :duration: 10
  :player_image: default/player1.png
  :player_shield_image: default/player1_neon.png
  :ball_image: default/asteroid.png
  :background_image: default/orange_nebula_stars.jpg
#level 7
- :from_left: 1
  :from_right: 1
  :duration: 10
  :player_image: default/player1.png
  :player_shield_image: default/player1_neon.png
  :ball_image: default/asteroid.png
  :background_image: default/orange_nebula_stars.jpg
#level 8
- :from_top: 3
  :from_bottom: 1
  :duration: 10
  :player_image: default/player1.png
  :player_shield_image: default/player1_neon.png
  :ball_image: default/asteroid.png
  :background_image: default/orange_nebula_stars.jpg
#level 9
- :from_custom:
     :count: 2
     :xinc: lambda {|x,y,xs,ys| 100*(Math.sin(y.to_f/100)) + xs}
     :yinc: lambda {|x,y,xs,ys| y + 10}
     :xinit: lambda {rand(600) + 100}
     :yinit: lambda {0}
  :duration: 10
  :player_image: default/player1.png
  :player_shield_image: default/player1_neon.png
  :ball_image: default/asteroid.png
  :background_image: default/orange_nebula_stars.jpg
#level 10
- :from_top: 3
  :from_left: 3
  :duration: 10
  :player_image: rainbow/unicorn.png
  :player_shield_image: rainbow/butterfly3.png
  :ball_image: rainbow/butterfly1.png
  :font_color: 0xFFFA5094
  :background_image: rainbow/rainbow_background.jpg